### ISSUE TITLE
Sleep instead of Shutdown?

### ISSUE THREAD

**Issue by RussianRonin** [akorb/SteamShutdown#12]
Any way to include a sleep instead of shutdown?

**Comment by akorb** [comment]
Thanks for your report. I like your idea. Thus I already implemented it in my local version. Unfortunately, I don't have the time now to test and upload it. But I will do that soon and let you know.

**Comment by akorb** [comment]
Added in version 1.8.0. Redownload from https://github.com/akorb/SteamShutdown/releases/latest

**Comment by akorb** [comment]
You can choose the action now in the new version (v1.8.0) https://github.com/akorb/SteamShutdown/releases/latest
