### ISSUE TITLE
Not Shutdown

### ISSUE THREAD

**Issue by ghost** [akorb/SteamShutdown#16]
Steamshutdown is working great on my PC, but not on my laptop
both are running Win10 64bit build 1703
On my laptop I did this cmd "shutdown /s /t 0" and it shutdown, and I run SteamShutdown as an admin
Btw this little software is very helpful, thanks for making this.
EDIT
Solved after reinstalling windows

**Comment by akorb** [comment]
I'm very glad you like it :)
