### ISSUE TITLE
Doesn't shutdown when preloading games

### ISSUE THREAD

**Issue by thegh0sts** [akorb/SteamShutdown#17]
I've been preloading Wolfenstein The New Colossus and as soon as it finished the preload it changed to "In Queue" and steam did not shut down. I'm assuming the app still think that the download is still not complete and hence does not shut down.

Is there a way to detect the "In Queue" status to make it shut down instead of sitting idle?

**Comment by akorb** [comment]
That's a tough question. I doubt there's an own StateFlag for this case. But let's try it.

Can you check the "StateFlags" value in your appmanifest_<ID>.acf file? It's in "..\Steam\steampps"?

For me it's the ID 650500. But I live in Germany and I only see the cut version. If you don't find this ID, try 612880.

**Comment by akorb** [comment]
Probably fixed with https://github.com/akorb/SteamShutdown/commit/aafab99498bf7cf7822527937f62b316cbc77057
Feel free to reopen this issue if this problem persists
