### ISSUE TITLE
When I open the .exe, nothing happens

### ISSUE THREAD

**Issue by philippsander** [akorb/SteamShutdown#2]
what is supposed to happen?

**Comment by akorb** [comment]
The dialog should show up. Have you Windows and .NET 4 running?

**Comment by philippsander** [comment]
I do have Windows 10.  I don't know if I have .NET 4 installed. I'm currently at work so I will have a look at it when I'm at home

**Comment by akorb** [comment]
Windows 10 has .NET 4 built-in as .NET 4.6
Thus no problem there. Very weird. I'll check it.

**Comment by rabross** [comment]
Same issue for me on win 10.

**Comment by akorb** [comment]
Hmm.. checked on a fresh Windows 7 and 10 system and everything works fine. Does the behavior change if you launch the program as administrator?

I guess you are on v1.4, aren't you?

**Comment by akorb** [comment]
Maybe you didn't unpack the zip file?

**Comment by tofrus** [comment]
thanks for sharing but i got same issue like the others, nothing happened, even if i run as admin. im on win 10 but once again thanks man

**Comment by philippsander** [comment]
it works now. should we close it or is anybody else having issues?

**Comment by tofrus** [comment]
yes i can open it now. maybe you can close it
