### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Doracoin** [akorb/SteamShutdown#21]
System.TypeInitializationException: “SteamShutdown.Steam”的类型初始值设定项引发异常。 ---> System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\username\Desktop\SteamApps\libraryfolders.vdf”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding)
   在 System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   在 System.IO.File.ReadAllLines(String path)
   在 SteamShutdown.Steam.GetLibraryPaths()
   在 SteamShutdown.Steam..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   在 SteamShutdown.CustomApplicationContext..ctor()
   在 SteamShutdown.Program.Main()

**Comment by akorb** [comment]
Thanks for your report.

Would you please post your registry values for the keys:
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam`
`HKEY_LOCAL_MACHINE\SOFTWARE\Valve\Steam`

You have a 64 bit system, right?

It seems your installation path of steam in the registry is set to `C:\Users\username\Desktop\` for some reason. Maybe you installed it there and moved the files by hand?

**Comment by Doracoin** [comment]
Yeah, is 64 bit and most of my application installed not at "System-Partition". That's mean not at `C:`. For my application will not lost after re-install Windows. And I'm just re-install Windows recently.

So that problem may occured at your program get the `null` from reg keys?

And I suggest that program can set 'Steam Path' by user mannualy.

Sorry, it may some bad grammar 😋

---

#### KEY_INFOS

``` cmd
reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam
    SteamPID    REG_DWORD    0x0
    TempAppCmdLine    REG_SZ
    TempAppPath    REG_SZ

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\Apps
```

``` cmd
reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\Apps

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\Apps\0
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\Apps\219740
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\Apps\431960
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Valve\Steam\Apps\CommonRedist
```

**Comment by akorb** [comment]
Can you check if with the newest release the problem still persists? (if it still happened)
