### ISSUE TITLE
Not detecting games updating in a library that is not located on C:

### ISSUE THREAD

**Issue by CivisMiles** [akorb/SteamShutdown#23]
SteamShutdown v2.2 is not detecting any steam downloads (Hitman 2 and Dying Light were updating not first time downloading if that makes a difference somehow).
I ran it from an admin account, tried manually running it as administrator, tried running it from Desktop, C:\Program Files (x86)\Steam, and D:\Programs\Games\Steam with both previous mentioned steps, tried starting it before the download, during the download, and before the Steam client had been launched.
After checking Steam.cs, as long as my C# is on point, it should detect the download location as it is a registered library and have no issues.
I haven't checked to see if it works but just doesn't show my downloads or if it doesn't work at all (slow internet on a 11GB update so i just haven't reached the point to see if it works yet)

Computer info:
Windows 10 64-bit (currently running the slow channel insider build Version 1903 Build 18362.10022)
SteamShutdown v2.2
Steam Client: API v019, Package 1570046470
Steam is installed on the default location and have registered libraries at:
C:\Program Files (x86)\Steam and D:\Programs\Games\Steam (both these drives are Samsung SSD's)

Edit: Confirmed that it doesn't shut down/sleep when download is completed even when set to Complete All Downloads

**Comment by CivisMiles** [comment]
Well this started working yesterday after a small update (I believe a windows update) and restart so I don't know what the issue was. I don't think it was the restart as i don't leave my computer running and restart it after almost any program installation.
So no more issue through mysterious means, my "favorite" way for issues to fix

**Comment by akorb** [comment]
Hello CivisMiles,

sorry for my late response. I'm not at home until next year.
I'm glad your issue has resolved itself. Still weird.

You're right about the fact that there are different states of "downloading". This should handle this: https://github.com/akorb/SteamShutdown/blob/master/SteamShutdown/App.cs#L29
This are all IDs I found by myself by experimenting, so I might still miss one ID for one specific situation. But it's always difficult to figure them out.

Good everything works for you again. Have a nice day.
