### ISSUE TITLE
Doesn't detect I'm downloading 2 games

### ISSUE THREAD

**Issue by ipisano** [akorb/SteamShutdown#25]
![8KM3uhO1GT](https://user-images.githubusercontent.com/18221957/77698474-f430fd80-6fb0-11ea-98b3-7131b6085448.png)
As title. I've tried moving up PUBG but it still doesn't detect that steam is also updating Borderlands 3.

**Comment by akorb** [comment]
Thanks for your report.

Can you please send me these files: ...\Steam\steamapps\appmanifest_*.acf

**Comment by ipisano** [comment]
Sure, but there are 2 issues with this:

1) The downloads are completed now
2) I have 2 libraries on different drives, look at the screenshot for more details.
![l5bIMmR6js](https://user-images.githubusercontent.com/18221957/77745795-39d6e000-701c-11ea-9641-68be34a519bd.png)

Does SteamShutdown only look at the "default" library instead of all of them maybe?

**Comment by akorb** [comment]
I just uploaded a new version with a new mechanism to check if a game is downloading. It should work more reliable now than before.
Since this is maybe related to this issue, I will close it. But as soon as the problem reoccures, feel free the reopen this issue.
