### ISSUE TITLE
"No games downloading"

### ISSUE THREAD

**Issue by Ronkn** [akorb/SteamShutdown#28]
Win10, steam is currently downloading a game. I have this program set to shutdown when downloads are complete, and to "complete all downloads". I've tried running this as admin, and I've tried shutting steam down, starting this program, then launching steam, and that didn't work either. 

Any ideas?  Thanks for your time.

**Comment by akorb** [comment]
Hello,

did the program detect correctly which games are downloading?

boggle247 <notifications@github.com> schrieb am Do., 21. Mai 2020, 03:46:

**Comment by Ronkn** [comment]
No it did not give any indication of the game that was downloading. Just said no games downloading.

**Comment by akorb** [comment]
Can you please send me the files: ...\Steam\steamapps\appmanifest_*.acf of the corresponding games which are downloading?
Maybe changed something with the state IDs or has new ones.

Which kind of download is it? A preload? update? First download?

**Comment by Ronkn** [comment]
Not at my pc but I'll try to get it tonight if possible.

Only downloading halo masterchief collection. Particularly the multi-player and campaign modes for halo 2.

**Comment by akorb** [comment]
Thanks. If I get the act file while it's still downloading I might be able
to fix it.

boggle247 <notifications@github.com> schrieb am Do., 21. Mai 2020, 15:23:

**Comment by Ronkn** [comment]
I had it downloading all night, so I'm going to guess it's all done already. Would you still want the acf file? Do you have to add the acf file for every game in the steam library in order for this to work? Is there a steam library online that you could link your program to, to reference and refresh periodically?

**Comment by akorb** [comment]
No it's not about the name. It's about the state ID. And maybe there's an
ID which indicates "downloading" but it's not in my program yet.
And I need to know the number otherwise I can't do something. Because there
is no documentation from Valve.

boggle247 <notifications@github.com> schrieb am Do., 21. Mai 2020, 16:37:

**Comment by Ronkn** [comment]
Gotcha. Well my wife confirmed my pc is shutdown so it still works at least, just wasn't showing the game that was downloading. So yeah I'll try to get you what you need. Is the acf file most likely gone now that it's finished downloading? If so, is there another file you could use instead?

**Comment by akorb** [comment]
Hmm okay. If the download is finished the acf files don't help me anymore. 
But as it seemed to work it looks more like a UI problem. I will check it

**Comment by akorb** [comment]
I just uploaded a new version with a new mechanism to check if a game is downloading. It should work more reliable now than before.
Since this is maybe related to this issue, I will close it. But as soon as the problem reoccures, feel free the reopen this issue.
