### ISSUE TITLE
Doesn't detect DLC's

### ISSUE THREAD

**Issue by ghost** [akorb/SteamShutdown#30]
Hello there, I hope you having a nice day. I'm downloading **[Life is Strange](https://store.steampowered.com/app/319630/Life_is_Strange__Episode_1/)**, but the program doesn't detect that I'm downloading anything. **Life is Strange** episode 1 is the main game, and the other 4 is considered DLC's, so I think that is the problem.

I'm using Windows 10 version 2004 64-bit, English_US.

**Life is Strange Appmanifest File (appmanifest_319630.acf)**

`"AppState"
{
	"appid"		"319630"
	"Universe"		"1"
	"name"		"Life is Strange™"
	"StateFlags"		"1044"
	"installdir"		"Life Is Strange"
	"LastUpdated"		"1591871622"
	"UpdateResult"		"4"
	"SizeOnDisk"		"2055902241"
	"buildid"		"2304417"
	"LastOwner"		"76561198163292436"
	"BytesToDownload"		"8686052976"
	"BytesDownloaded"		"551647056"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"ScheduledAutoUpdate"		"0"
	"InstalledDepots"
	{
		"319631"
		{
			"manifest"		"1504133382031970604"
		}
	}
	"MountedDepots"
	{
		"319631"		"1504133382031970604"
	}
	"SharedDepots"
	{
		"228981"		"228980"
		"228982"		"228980"
		"228984"		"228980"
		"228990"		"228980"
		"229032"		"228980"
		"229033"		"228980"
	}
	"StagedDepots"
	{
		"329880"
		{
			"manifest"		"6686257525367030622"
			"size"		"1654004951"
			"dlcappid"		"329880"
		}
	}
	"DlcDownloads"
	{
		"329880"
		{
			"BytesDownloaded"		"551647056"
			"BytesToDownload"		"1443302064"
		}
		"329910"
		{
			"BytesDownloaded"		"0"
			"BytesToDownload"		"1874391840"
		}
		"329920"
		{
			"BytesDownloaded"		"0"
			"BytesToDownload"		"2421583360"
		}
		"329930"
		{
			"BytesDownloaded"		"0"
			"BytesToDownload"		"2946775712"
		}
	}
	"UserConfig"
	{
		"language"		"english"
	}
}
`

btw, the program is working fine with other games, and I want to thank you for making such a useful tool. I wish you the best.

**Comment by akorb** [comment]
~~Thanks for your report. Can you please check if the following version works as expected?~~

~~[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/4765855/SteamShutdown.zip)~~

Nope, doesn't work. I'm working on an update.

**Comment by akorb** [comment]
This should work now. Could you verify it please?

[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/4766049/SteamShutdown.zip)

**Comment by ghost** [comment]
Yes, the program works! Thanks again.

![steamshutdownworking](https://user-images.githubusercontent.com/35402499/84454904-93869800-ac64-11ea-86aa-57276559db20.png)

**Comment by akorb** [comment]
Thank you very much for your report. It got me an idea and I think it's way more reliable now than before in many cases. 😄
