### ISSUE TITLE
[minor]points to incorrect page 

### ISSUE THREAD

**Issue by TWood-IRL** [akorb/SteamShutdown#31]
points to incorrect page
https://steamshutdown.andreas-korb.de/

download zip 
points to incorrect url 
https://github.com/akorb/SteamShutdown/releases/download/v2.3.4/SteamShutdown.zip

>https://github.com/akorb/SteamShutdown/releases/download/v2.3.4/SteamShutdown.zip

>not found

**Comment by akorb** [comment]
Thank you very much for notifying me!

Some time ago I moved from downloading a zip to directly download the exe and didn't change the link on this page.

Fixed :)
