### ISSUE TITLE
Where do I donate to?

### ISSUE THREAD

**Issue by divStar** [akorb/SteamShutdown#32]
This tool does something Vavle apparently hasn't been willing to do for the last decade or longer... I don't yet know if it works, but it's late at night and I am going to sleep and since I got a new PC, I am now installing about 400gb of games. My internet is fast, but it'll still take many hours - so I'll see if this anti-sleep-before-Steam-finished tool works.

If it does though, I'd gladly toss over a bear (or a glass of wine or whiskey - whatever it is you prefer) by donating something. Just in case: where can I send some PayPal money to?

**Comment by akorb** [comment]
Oh wow, this will be a stress test for SteamShutdown. I hope everything worked for you. Please let me know.

If everything worked for you, my PayPay account is andreas.d.korb@gmail.com
Since I'm german, well, you probably already know it from here 🍺
Beer costs here only around 0.50 € = $0.60

**Comment by divStar** [comment]
Wow - ich bin auch aus Deutschland, Nürnberg. Hat alles super geklappt. Danke!

**Comment by akorb** [comment]
I'm very happy everything worked for you!

Thanks for your donation. That was the first donation ever for me. So thank you very much!
