### ISSUE TITLE
Crash when startup

### ISSUE THREAD

**Issue by luckyjinx** [akorb/SteamShutdown#33]
2021/3/16 1:10:13: System.MissingMethodException: 找不到方法:“!!0[] System.Array.Empty()”。
   在 SteamShutdown.RPC.StartServer()
   在 SteamShutdown.SteamShutdown.EnsureSingleInstance()
   在 SteamShutdown.SteamShutdown.Main()

**Comment by luckyjinx** [comment]
the system language is Chinese,Windows 8.1,but on the windows 10 it's working fine

**Comment by akorb** [comment]
Thanks for your report.
Is it possible that .NET 4.6 is not installed on your Windows 8.1 machine?

https://www.microsoft.com/en-us/download/details.aspx?id=53345
