### ISSUE TITLE
Crash upon start-up 

### ISSUE THREAD

**Issue by Parzival3971** [akorb/SteamShutdown#36]
Hi team,

When running the .exe, the program encounters and error upon star up.

**PC Specs**
AMD Ryzen 5 5600X
Edition	Windows 10 Home
Version	21H1
Installed on	‎31/‎03/‎2021
OS build	19043.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0
 

[SteamShutdown_Log.txt](https://github.com/akorb/SteamShutdown/files/6715013/SteamShutdown_Log.txt)

**Comment by akorb** [comment]
Thanks for your report. Can you try the version I posted here please? I think it's the same problem.
https://github.com/akorb/SteamShutdown/issues/34#issuecomment-864575387

I didn't have time yet to push the changes as a new release. I'll do so soon.

**Comment by Parzival3971** [comment]
> Thanks for your report. Can you try the version I posted here please? I think it's the same problem.
> [#34 (comment)](https://github.com/akorb/SteamShutdown/issues/34#issuecomment-864575387)
> 
> I didn't have time yet to push the changes as a new release. I'll do so soon.

Hi @akorb,

That's working for me 😃 

Thanks for the lightning fast response and such an awesome program 👍
