### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Rharim** [akorb/SteamShutdown#38]
I used .exe version. I'm on Win10 x64, sys language set to Polish.
[SteamShutdown_Log.txt](https://github.com/akorb/SteamShutdown/files/6719365/SteamShutdown_Log.txt)

**Comment by CrysoK** [comment]
Same crash here.
[SteamShutdown_Log.txt](https://github.com/akorb/SteamShutdown/files/6719824/SteamShutdown_Log.txt)
Windows 10 x64 Version 20H2

It doesn't happen on v2.3.4

**Comment by akorb** [comment]
Sorry to hear that!
I think I already know what's causing it.

Could someone of you please send me this file:
"C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf"

**Comment by Rharim** [comment]
Here you go.
[libraryfolders.zip](https://github.com/akorb/SteamShutdown/files/6719863/libraryfolders.zip)

**Comment by akorb** [comment]
Could you please verify that this version works again?
[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/6719879/SteamShutdown.zip)

**Comment by Rharim** [comment]
Can't do it - my pc is stubborn and say it's a virus. That said I can't even download it.

**Comment by akorb** [comment]
Maybe this works?
[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/6719918/SteamShutdown.zip)

**Comment by Rharim** [comment]
It starts now. But I tried it twice alredy and it do not turn off PC after download finish. It should work without admin, right?

**Comment by MatchTerm** [comment]
Same thing here
[SteamShutdown_Log.txt](https://github.com/akorb/SteamShutdown/files/6738003/SteamShutdown_Log.txt)

**Comment by akorb** [comment]
[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/6742866/SteamShutdown.zip)

Could you please check if this version works again?

**Comment by troy0h** [comment]
Hi, I'm getting the same error
`30/06/2021 23:37:02: System.TypeInitializationException: The type initializer for 'SteamShutdown.Steam' threw an exception. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'ContainsKey'
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at SteamShutdown.Steam.GetLibraryPaths(String installationPath)
   at SteamShutdown.Steam..cctor()
   --- End of inner exception stack trace ---
   at SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   at SteamShutdown.CustomApplicationContext..ctor()
   at SteamShutdown.SteamShutdown.Main()`
v2.3.4 also works fine for me, and the newest zip you sent here seems to work at the moment

**Comment by akorb** [comment]
I just pushed a new update. I hope it fixed all the problems you encounter

**Comment by CaliMali** [comment]
[SteamShutdown_Log.zip](https://github.com/akorb/SteamShutdown/files/6909070/SteamShutdown_Log.zip)
cant launch
