### ISSUE TITLE
Game mistakenly identified as downloading

### ISSUE THREAD

**Issue by CrysoK** [akorb/SteamShutdown#40]
It has happened a couple of times already with the same game: "Half-Life". It's not even in my library lol.
![image](https://user-images.githubusercontent.com/57516378/124553065-aa1d0580-de0a-11eb-8818-354c4571c240.png)
How can I make it disappear manually? For example editing some file.

**Comment by akorb** [comment]
In your SteamApps folder are *.acf files. You can open them with a simple text editor. One of these files should contain the "Half-Life" as the application name. Probably the file is called `appmanifest_70.acf`.
If the game is not installed, you can try deleting this file. Or maybe first sharing it here, that I can have a look into it

**Comment by CrysoK** [comment]
Deleting the file worked. Thanks.
[appmanifest_70.zip](https://github.com/akorb/SteamShutdown/files/6793898/appmanifest_70.zip)

**Comment by akorb** [comment]
Graet! The stateflags field of the file you sent me says 70. Which is exactly the ID of Half-Life. This could be coincidence, but maybe Steam had a bug and wrote the app id into the stateflags for some reason. I didn't see this value for the stateFlags before. But thanks for reporting and sending the file. If this happens again, this might become very helpful.
