### ISSUE TITLE
Shows a non-existing download

### ISSUE THREAD

**Issue by pabsi** [akorb/SteamShutdown#47]
Hello there,
an issue I have is that this program shows a non-existing download:
![image](https://user-images.githubusercontent.com/5247611/142730285-db44b629-e970-44bd-a520-dce01baa2107.png)
![image](https://user-images.githubusercontent.com/5247611/142730328-502f12b2-9999-4d64-9516-bfd481c96c5a.png)

Also, even if I handpick the downloads manually, it does not shutdown the computer after those are finished.

Any help is appreciated.

Here's the `acf` in case it helps:

```"AppState"
{
	"appid"		"1003800"
	"Universe"		"1"
	"LauncherPath"		"D:\\Games\\Steam\\steam.exe"
	"name"		"Gang Beasts Soundtrack"
	"StateFlags"		"70"
	"installdir"		"Gang Beasts Soundtrack"
	"LastUpdated"		"1579475368"
	"UpdateResult"		"0"
	"SizeOnDisk"		"0"
	"buildid"		"3713383"
	"LastOwner"		"0"
	"BytesToDownload"		"0"
	"BytesDownloaded"		"0"
	"BytesToStage"		"0"
	"BytesStaged"		"0"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"ScheduledAutoUpdate"		"0"
	"InstalledDepots"
	{
	}
	"UserConfig"
	{
		"highqualityaudio"		"1"
	}
}
```

Thank you so much.

**Comment by akorb** [comment]
[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/8144794/SteamShutdown.zip)
Is it fixed with this version?

**Comment by pabsi** [comment]
Hello @akorb 
first of all, thank you for working on this appreciated :) 

This new version fixed the non-existing download. It's gone away.

But my system didn't shutdown upon finishing all downloads. Not sure if I have to run it as admin, or do something special.
I just opened the app after having a game downloading (Lost Ark, which identified), and I clicked "Complete all downloads"  and action "Shutdown", and nothing happened.

Does this app log to any file or anything I can look at to provide more info or debug logs?

**Comment by akorb** [comment]
"Complete all downloads" needs to be ticked while the downloads are running and when the downloads are to be finished.

Yesterday, I released a new official release, does it work with it?
https://github.com/akorb/SteamShutdown/releases/download/v2.4.0/SteamShutdown.exe
[SteamShutdown.zip](https://github.com/akorb/SteamShutdown/files/8148587/SteamShutdown.zip)

If not, I created a version which creates a debug log called `debugging.txt` on the desktop.

**Comment by pabsi** [comment]
Well I can't tell if it is the new release or the fact that I run it as admin, but this time I downloaded another game, and it shutdown perfectly. I'll try without admin again if you want me to

Thanks again!

PS: feel free to close this issue, and If I encounter any issues I'll report with debug logs etc. Thanks!

**Comment by akorb** [comment]
The program does not require admin privileges. At least, it shouldn't :)

That's an interesting observation. Could you verify if this problem only persists for one specific game?

**Comment by pabsi** [comment]
Sorry for the delay. I not always use my Windows computer :) 

I just tested it. I had 2 downloads pending when I opened the program (using 2.4.0.0).

I checked one of them (Among Us, if it matters), and didn't select anything else (Action -> Shutdown, is the default). Waited until the download finished. A few seconds after it did, the compute shutdown.

It works wonders :) 

Brilliant app, you rock!
