### ISSUE TITLE
Multiple downloads

### ISSUE THREAD

**Issue by Motzumoto** [akorb/SteamShutdown#49]
Does this program work with multiple downloads?
![image](https://user-images.githubusercontent.com/45925152/157539836-b983df91-64a2-4a1e-a3f7-13337c751e34.png)
I have quite a few games downloading, this will take upwards of 8 hours thanks to my slow download speed.

**Comment by akorb** [comment]
It should work yes.
Just ensure the "Complete all downloads" is ticked

Chris ***@***.***> schrieb am Mi., 9. März 2022, 22:33:

**Comment by Motzumoto** [comment]
> It should work yes. Just ensure the "Complete all downloads" is ticked

okie dokie :D
