### ISSUE TITLE
Space Pirates and Zombies breaks app

### ISSUE THREAD

**Issue by NickHeap** [akorb/SteamShutdown#6]
Space Pirates and Zombies breaks the app as it uses AppID.
Line 83 in Steam.cs throws the error.
ID = int.Parse((json.appid ?? json.appID).ToString()),

**Comment by akorb** [comment]
Can you attach its acf file please? It's probably the "appmanifest_107200.acf" file in ..\Steam\SteamApps\

**Comment by NickHeap** [comment]
Sorry for the delay. Here is the file.
[appmanifest_107200.zip](https://github.com/akorb/SteamShutdown/files/587524/appmanifest_107200.zip)

**Comment by akorb** [comment]
I released a new release (v1.5) which fixes the issue :)
